import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

import { wrapper } from "@/store";
import actions from "@/store/blog/actions";

const { getUserRequest } = actions;

export default function Home(props: any) {
  const [count, setCount] = useState(0);
  const BlogSport = useSelector((state: any) => state?.Blog);
  const test = useRef(1);
  const dispatch = useDispatch();

  const handle = () => {
    test.current += 1;
    console.log(test.current);
  };
  console.log(props, "page Hello");
  console.log(BlogSport, "BlogSport Hello");

  // useEffect(() => {
  //   if (!(BlogSport?.payload?.profile?.length > 0)){
  //     console.log("first");
  //     dispatch(getUserRequest());
  //   }
  // }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>{count}</p>
        <button onClick={() => handle()}>Count</button>
        <Link href={"/"} style={{ height: "200rem", background: "red" }}>
          Index
        </Link>
      </main>
    </>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    store.dispatch(getUserRequest());
    const reduxState = store.getState().Blog;
    return { props: reduxState };
  },
);
